# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8081
  servlet:
    # 应用的访问路径
    context-path: /uapi
  # Spring配置
spring:
  ai:
    openai:
      # openai的api-key
      api-key: sk-4ecd546690124085b63316161bb6de39
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat


  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 9


  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/sx-easy?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 1234

  application:
    name: SXEasy






# MyBatisPlus配置
# https://baomidou.com/config/
mybatis-plus:
  # 自定义配置 是否全局开启逻辑删除 关闭后 所有逻辑删除功能将失效
  enableLogicDelete: true


#springai日志
#logging:
#  level:
#    org.springframework.Ai.chat.client.advisor: debug



#minio
# MinIO 配置
minio:
  endpoint: http://127.0.0.1:9090     # MinIO服务地址
  bucketName: test                     # 存储桶bucket名称
  accessKey: root                         # 用户名
  secretKey: 123456789                     # 密码
  imgSize: 1024                           # 图片大小限制，单位：m
  fileSize: 1024                          # 文件大小限制，单位：m
  enable: false #是否开启


#本地上传配置
xiaou:
  upload:
    local-path: E:/ck/SXEasy-backend/upload  # 上传文件的本地路径
    access-prefix: /upload-files  # 访问文件的URL前缀
    service-host: http://localhost:8081  # 本地服务的host

#腾讯云上传配置
tencent:
  cos:
    secretId: xxx
    secretKey: xxx
    region: ap-chengdu
    bucketName: 11-1305448902
    base-url: xxx
#阿里云上传配置
aliyun:
  oss:
    bucket-name: blogman
    endpoint: oss-cn-beijing.aliyuncs.com
    key-id: LTAI5tKcgLtNZSx2mi6tXY8z
    key-secret: sQQRUPJEB3RFFgGnxxBOmHP4uiCuXQ
